// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vidya.Infrastructure.Data;

#nullable disable

namespace Vidya.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250203165941_UpdateUsersTable")]
    partial class UpdateUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vidya.Domain.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("AddOnDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuthAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthDel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthLstEdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DelOnDt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EditOnDt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsAdmin")
                        .HasColumnType("int");

                    b.Property<int>("MasterID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("tbluser");
                });
#pragma warning restore 612, 618
        }
    }
}
